import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-50 flex flex-col font-sans text-slate-900">
      <Navbar />
      
      <main className="flex-1 py-16 md:py-24">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-4xl font-extrabold tracking-tight mb-4">Terms of Service</h1>
          <p className="text-slate-500 mb-12">Last updated: {new Date().toLocaleDateString()}</p>
          
          <div className="prose prose-slate max-w-none">
            <p>
              Welcome to ClassCraft Presentations. Whether you are an educator, student, or school administrator, using our platform assumes you are agreeing to these Terms of Service. Be sure to read them carefully as they influence the way you use our educational presentation-maker.
            </p>

            <h2>Acceptable Use</h2>
            <p>
              By accessing ClassCraft Presentations, you agree that you will only use the AI builder for legitimate, non-malicious intent. When uploading PDFs, Word documents, YouTube videos, or transcripts, you agree not to submit material that violates copyrights, promotes hate speech, or bypasses any digital security protection. 
            </p>

            <h2>Intellectual Property</h2>
            <p>
              The AI models assist in generating slides based on the source material you upload. You are strictly responsible for having the right to upload classroom reading lists, third-party YouTube videos, and similar resources. Our template designs and core layout mechanisms belong to ClassCraft Presentations; however, the generated content, based entirely on your uploads, is yours to edit and distribute amongst your classrooms.
            </p>

            <h2>Educational Usage Disclaimers</h2>
            <p>
              Classroom presentations generated by artificial intelligence may occasionally include inaccuracies or misinterpretations. As an educator or student, you are responsible for fact-checking all exported PowerPoints, Word documents, and PDFs before grading, submitting, or utilizing them formally. 
            </p>

            <h2>Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, ClassCraft Presentations is not liable for indirect or consequential damages arising from the use of our services (e.g., failed assignments, technological delays during a semester, or incorrect lesson grading). The platform is provided "as is."
            </p>

            <h2>Termination</h2>
            <p>
              We reserve the absolute right to suspend or terminate accounts that breach these Terms of Service without notice. Accounts discovered to be programmatically abusing our systems or attempting to bypass payment quotas limit fair-usage for other education users.
            </p>

            <h2>Governing Law</h2>
            <p>
              These Terms are governed and construed in accordance with the laws of the jurisdiction in which ClassCraft Presentations operates, without regard to its conflict of law provisions. Any legal matters regarding these Terms of Service will be settled there. 
            </p>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
